### PR TITLE
Adds adm-zip as a dependency

### PR DESCRIPTION
**Pull request by trycrmr**
*Issue #, if available:* Issue #1 

*Description of changes:* Adds adm-zip with type definitions as a dependency. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by ottokruse** [comment]
Hi @trycrmr. Let's make a dev dependency out of this, agree?

**Comment by ottokruse** [comment]
Looking at this again, I see the dependencies are already listed in src/cfn-custom-resources/lambda-code-update/package.json. I think that is the right place for these dependencies.

The issue is, when you do `npm install` in the workspace root, the dependencies for lower level directories are not installed. That would have to be done manually.

We can fix that by (e.g.) adding a `postinstall` step to the main package.json, that would go into the subdirs and do `npm install` there. Then an `npm install` in the workspace root will trigger all installs.

Would you be interested in implementing that `postinstall` step?

(Can maybe steal some code from the `update-dependencies` script I just added to package,json)

**Comment by trycrmr** [comment]
Makes sense to me! I see the [`update-dependencies` line](https://github.com/aws-samples/cloudfront-authorization-at-edge/blob/4b34cb4b3b3b0bad24d70c1dbe6f8c409d77551a/package.json#L12). Should have updates for you later today.

**Comment by trycrmr** [comment]
A few things worth noting: 

- Apparently [--ignore-scripts ignores preinstall/postinstall/etc scripts of dependencies of dependencies](https://npm.community/t/ignore-scripts-ignores-all-scripts/1403). Doesn't appear to be an issue here, but worth raising in case dependencies are added to dependent package.jsons that have preinstall/postinstall/etc install scripts. --ignore-scripts prevents an install loop. 
- Including the current directory in the postinstall script caused npm install to be run twice on the current directory. Removed this because that's redundant.
- Running npm ci on the top-level won't run npm ci within the dependent directories if that's what you're hoping for. If in the future there is some CI for this setup that'd be a consideration. 
- Package-lock bonus commit in spite of those dependencies not having any node_modules installed. I guess the first version of those package-locks indicates to install nothing :smiley:

**Comment by ottokruse** [comment]
Looks good to me! Thank you

**Pull request merged**
