### PR TITLE
Update template.yaml to use BucketPolicy

### PR DESCRIPTION
**Pull request by sambler**
Replace legacy S3 AccessControl with a bucket policy.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by sambler** [comment]
ignore the noise, there is already a bucket policy in place that works, so bring this down to removing the legacy AccessControl

**Comment by ottokruse** [comment]
Sure, thanks. What's the benefit of not specifying private? Just cleaner (fine reason) as ACLs are deprecated, or will there be an actual effect too?

**Comment by sambler** [comment]
At the time I got a fail to create bucket, needed to remove it to create the stack.

A quick test of only a bucket works with sam and cfn, so it may have been a bucket policy I added that conflicted with the Accesscontrol.

**Comment by ottokruse** [comment]
Okay sure. And what's the benefit of removing AccessControl=Private now from the template? What will that improve?

I think it's a good idea because that property is deprecated but just wondering if it has a tangible benefit besides that.

**Comment by sambler** [comment]
Turns out it would only make it easier to add other bucket policies, so not directly effecting this stack now.

I only submitted because I thought having the AccessControl was preventing the stack create, which I found to be a conflict with my modifications.

**Comment by ottokruse** [comment]
Aight, well let's get rid of a deprecated property 🤘🏻

**Pull request merged**
