### PR TITLE
Added Regex support for multi-region for Cognito Userpool

### PR DESCRIPTION
**Pull request by NinitoAS**
*Issue #, if available:*

*Description of changes:*
Fixes regex so it supports multi-region Cognito Userpools. Still does not support GOV regions (and it probably doesn't need to either).

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by ottokruse** [comment]
Oops closed by accident, reopened

**Comment by ottokruse** [comment]
Thanks for the PR!

Looking at the region list, we can sharpen the regex further, to something like:

<two chars>-<eight chars>-<one char>

That would work for all regions where Cognito User Pools is currently available.

However, to be really future proof, the Cognito User Pool id seems to have always have this pattern:

<regioncode><underscore><id>

So maybe we should just focus on that underscore as being the delimiter between region and id, in a regex like this:

^(\S+?)_\S+$

What do you think?

**Comment by NinitoAS** [comment]
> Thanks for the PR!
> 
> Looking at the region list, we can sharpen the regex further, to something like:
> 
> `<two chars>-<eight chars>-<one char>`
> 
> That would work for all regions where Cognito User Pools is currently available.
> 
> However, to be really future proof, the Cognito User Pool id seems to have always have this pattern:
> 
> `<regioncode><underscore><id>`
> 
> So maybe we should just focus on that underscore as being the delimiter between region and id, in a regex like this:
> 
> `^(\S+?)_\S+$`
> 
> What do you think?

I believe this is the best solution as well

**Comment by ottokruse** [comment]
Allright, I'll leave the honors to you to get that in

**Comment by NinitoAS** [comment]
The regex you sent needed some additional characters (escape /regex/). I updated it and tested with a few different strings. Works like a charm.

**Comment by ottokruse** [comment]
Great! I'll do a test deployment later, validate, merge this PR and publish to SAR

**Comment by ottokruse** [comment]
Works! Merging

**Comment by NinitoAS** [comment]
Left you a message on Reddit regarding support for other Cognito regions (which is what I am trying to achieve). Let me know if you have time for a chat

**Pull request merged**
