### PR TITLE
Add lambda:TagResource permission

### PR DESCRIPTION
**Pull request by ottokruse**
_Issue #, if available:_ N/A

_Description of changes:_ Add lambda:TagResource permission (so e.g. SAM can add the "create with SAM" tag)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by mohanvarupula** [comment]
@ottokruse Which version consists of this change? IAM policies created through v2.1.4 doesn't possess this permission.

**Comment by ottokruse** [comment]
That should have made it in in v2.1.2 and as far as I can see it did: https://github.com/aws-samples/cloudfront-authorization-at-edge/commit/f069beb8c310a3f57a77425a605d874e093513ae

What troubles are you running into?

**Comment by ottokruse** [comment]
Confirm that you have these lines in your `template.yaml` ?:

https://github.com/aws-samples/cloudfront-authorization-at-edge/blob/715e38cd98efd40727f9fa51dae61d78be9aa70c/template.yaml#L446-L447

And confirm that they are indeed present on the `UsEast1DeploymentHandler` role?

**Comment by mohanvarupula** [comment]
I'm using the below template. I'm not creating UsEast1DeploymentHandler role. Please suggest if I have create any other resources.

**TEMPLATE**
`AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Example stack that shows how to reuse the serverless application and include your own resources

Parameters:
  SemanticVersion:
    Type: String
    Description: Semantic version of the back end
    Default: "2.1.5"

  UserPoolArn:
    Type: String
    Description: Specify the ARN of an existing user pool to use that one instead of creating a new one. If specified, then UserPoolClientId must also be specified. Also, the User Pool should have a domain configured

  UserPoolClientId:
    Type: String
    Description: Specify the ID of an existing user pool client to use that one instead of creating a new one. If specified, then UserPoolArn must also be specified. Note new callback URL's will be added to the pre-existing user pool client

  HttpHeaders:
    Type: String
    Description: The HTTP headers to set on all responses from CloudFront. Defaults are illustrations only and contain a report-only Cloud Security Policy -- adjust for your application
    Default: "{}"

  EnableSPAMode:
    Type: String
    Description: Set to 'false' to disable SPA-specific features (i.e. when deploying a static site that won't interact with logout/refresh)
    Default: "true"
    AllowedValues: ["true", "false"]

Resources:
  LambdaEdgeProtection:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:520945424137:applications/cloudfront-authorization-at-edge
        SemanticVersion: !Ref SemanticVersion
      Parameters:
        CreateCloudFrontDistribution: "false"
        HttpHeaders: !Ref HttpHeaders
        UserPoolArn: !Ref UserPoolArn
        UserPoolClientId: !Ref UserPoolClientId
        EnableSPAMode: !Ref EnableSPAMode

Outputs:
  CheckAuthHandler:
    Description: Lambda@Edge function 
    Value: !GetAtt LambdaEdgeProtection.Outputs.CheckAuthHandler
  HttpHeadersHandler:
    Description: Lambda@Edge function 
    Value: !GetAtt LambdaEdgeProtection.Outputs.HttpHeadersHandler
  ParseAuthHandler:
    Description: Lambda@Edge function 
    Value: !GetAtt LambdaEdgeProtection.Outputs.ParseAuthHandler
  RefreshAuthHandler:
    Description: Lambda@Edge function 
    Value: !GetAtt LambdaEdgeProtection.Outputs.RefreshAuthHandler
  SignOutHandler:
    Description: Lambda@Edge function 
    Value: !GetAtt LambdaEdgeProtection.Outputs.SignOutHandler`

**Comment by ottokruse** [comment]
That looks good I think.

For a quick solution, you can solve your issue by opening the role `lambda-auth-xxx-inf-front-UsEast1DeploymentHandler-X7PO5JQOZ3EI` in AWS IAM in the console and just add these two permission there:

https://github.com/aws-samples/cloudfront-authorization-at-edge/blob/715e38cd98efd40727f9fa51dae61d78be9aa70c/template.yaml#L446-L447

And then deploy again.

For figuring out why you need to add those permissions manually, because you shouldn't have to, we need to find out why the serverless application in your case doesn't use the right template.

**Comment by ottokruse** [comment]
```aws serverlessrepo create-cloud-formation-template --application-id arn:aws:serverlessrepo:us-east-1:520945424137:applications/cloudfront-authorization-at-edge --semantic-version 2.1.5```

That gives me a proper template that includes the needed permissions. Not sure why your update does not work then.

**Comment by mohanvarupula** [comment]
I have given permissions manually to the role and everything is working fine 😒

**Comment by ottokruse** [comment]
Ok great.

If you wanna pursue root cause analysis:
You should see a nested stack for the solution in the AWS CloudFormation console. If you go there and click on template, you see the CloudFormation template with which it was deployed. Can you share that here? Should hopefully reveal some insights.

**Comment by mohanvarupula** [comment]
Cloudformation Template:

**Comment by ottokruse** [comment]
Not that one, but the one for the nested stack, it should like like [template.yaml](../template.yaml)
Let's see if the right permissions are in there

**Comment by mohanvarupula** [comment]
I could see that the nested stack is using my previous version v2.0.6. Not sure why it is not using v2.1.5. Because of this the permissions are not updated based on the latest version. Please find the below resources in the nested stack.

  UsEast1DeploymentHandler:
    Type: 'AWS::Lambda::Function'
    Condition: RegionIsNotUsEast1
    Properties:
      Code:
        S3Bucket: awsserverlessrepo-changesets-xxx
        S3Key: >-
          xxx/arn:aws:serverlessrepo:us-east-1:520945424137:applications-cloudfront-authorization-at-edge-versions-2.0.6/xxxxxxx
      Handler: index.handler
      Role: !GetAtt 
        - UsEast1DeploymentHandlerRole
        - Arn
      Runtime: nodejs14.x
      Timeout: 900
      Tags:
        - Key: 'lambda:createdBy'
          Value: SAM
  UsEast1DeploymentHandlerRole:
    Type: 'AWS::IAM::Role'
    Condition: RegionIsNotUsEast1
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
        - PolicyName: UsEast1DeploymentHandlerRolePolicy0
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'cloudformation:CreateChangeSet'
                  - 'cloudformation:CreateStack'
                  - 'cloudformation:DeleteChangeSet'
                  - 'cloudformation:DeleteStack'
                  - 'cloudformation:DescribeChangeSet'
                  - 'cloudformation:DescribeStacks'
                  - 'cloudformation:ExecuteChangeSet'
                  - 'cloudformation:UpdateStack'
                Resource:
                  - !Ref 'AWS::StackId'
                  - !Sub >-
                    arn:${AWS::Partition}:cloudformation:us-east-1:${AWS::AccountId}:stack/${AWS::StackName}/*
                  - !Sub >-
                    arn:${AWS::Partition}:cloudformation:us-east-1:${AWS::AccountId}:changeset/${AWS::StackName}/*
              - Effect: Allow
                Action: 'cloudformation:GetTemplate'
                Resource: !Ref 'AWS::StackId'
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:PutObject'
                  - 's3:CreateBucket'
                  - 's3:DeleteBucket'
                Resource: !Sub 'arn:${AWS::Partition}:s3:::*-authedgedeploymentbucket-*'
              - Effect: Allow
                Action: 'lambda:GetFunction'
                Resource:
                  - !GetAtt 
                    - ParseAuthHandler
                    - Arn
                  - !GetAtt 
                    - CheckAuthHandler
                    - Arn
                  - !GetAtt 
                    - HttpHeadersHandler
                    - Arn
                  - !GetAtt 
                    - RefreshAuthHandler
                    - Arn
                  - !GetAtt 
                    - SignOutHandler
                    - Arn
              - Effect: Allow
                Action:
                  - 'lambda:GetFunction'
                  - 'lambda:CreateFunction'
                  - 'lambda:DeleteFunction'
                  - 'lambda:UpdateFunctionCode'
                  - 'lambda:UpdateFunctionConfiguration'
                Resource:
                  - !Sub >-
                    arn:${AWS::Partition}:lambda:us-east-1:${AWS::AccountId}:function:*-CheckAuthHandler-*
                  - !Sub >-
                    arn:${AWS::Partition}:lambda:us-east-1:${AWS::AccountId}:function:*-ParseAuthHandler-*
                  - !Sub >-
                    arn:${AWS::Partition}:lambda:us-east-1:${AWS::AccountId}:function:*-RefreshAuthHandler-*
                  - !Sub >-
                    arn:${AWS::Partition}:lambda:us-east-1:${AWS::AccountId}:function:*-SignOutHandler-*
                  - !Sub >-
                    arn:${AWS::Partition}:lambda:us-east-1:${AWS::AccountId}:function:*-HttpHeadersHandler-*
              - Effect: Allow
                Action: 'iam:PassRole'
                Resource: !GetAtt 
                  - LambdaEdgeExecutionRole
                  - Arn
      Tags:
        - Key: 'lambda:createdBy'
          Value: SAM

**Comment by mohanvarupula** [comment]
@ottokruse Any idea why it is using the old version 2.0.6 instead of 2.1.5? I have few other environments already running on 2.0.6 in the same AWS account. Will this have an impact?

**Comment by ottokruse** [comment]
No idea yet. Will try to reproduce it and see if I run into the same.

**Comment by ottokruse** [comment]
Can't imagine it would have any impact on other stacks

**Pull request merged**
